// Auto-generated by hub-codegen
// Do not edit manually

export interface Capabilities {
  contextWindow: number;
  functions?: boolean;
  jsonMode?: boolean;
  maxOutputTokens: number;
  multimodal?: boolean;
  streaming?: boolean;
  systemPrompt?: boolean;
  vision?: boolean;
}

/** Chat response started */
export interface ChatEventChatStart {
  type: 'chat_start';
  coneId: string;
  /** Position of the user message node */
  userPosition: Position;
}

/** Chat content chunk (streaming) */
export interface ChatEventChatContent {
  type: 'chat_content';
  coneId: string;
  content: string;
}

/** Chat response complete */
export interface ChatEventChatComplete {
  type: 'chat_complete';
  coneId: string;
  /** The new head position (tree + response node) */
  newHead: Position;
  /** Total tokens used (if available) */
  usage: ChatUsage | null;
}

export interface ChatEventError {
  type: 'error';
  message: string;
}

/** Events emitted during cone.chat (streaming) */
export type ChatEvent = ChatEventChatStart | ChatEventChatContent | ChatEventChatComplete | ChatEventError;

export function isChatEventChatStart(e: ChatEvent): e is ChatEventChatStart { return e.type === 'chat_start'; }
export function isChatEventChatContent(e: ChatEvent): e is ChatEventChatContent { return e.type === 'chat_content'; }
export function isChatEventChatComplete(e: ChatEvent): e is ChatEventChatComplete { return e.type === 'chat_complete'; }
export function isChatEventError(e: ChatEvent): e is ChatEventError { return e.type === 'error'; }

/** Token usage information */
export interface ChatUsage {
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
}

/** Cone configuration - defines an cone's identity and behavior */
export interface ConeConfig {
  /** Created timestamp */
  createdAt: number;
  /** The canonical head - current position in conversation tree
This couples tree_id and node_id together */
  head: Position;
  /** Unique identifier for this cone */
  id: string;
  /** Additional configuration metadata */
  metadata?: unknown;
  /** Model ID to use (e.g., "gpt-4o-mini", "claude-3-haiku-20240307") */
  modelId: string;
  /** Human-readable name */
  name: string;
  /** System prompt / instructions for the cone */
  systemPrompt?: string | null;
  /** Last updated timestamp */
  updatedAt: number;
}

/** Lookup cone by its human-readable name */
export interface ConeIdentifierByName {
  type: 'by_name';
  /** Cone name (supports partial matching, e.g., "assistant" or "assistant#550e") */
  name: string;
}

/** Lookup cone by its UUID */
export interface ConeIdentifierById {
  type: 'by_id';
  /** Cone UUID */
  id: string;
}

/** Identifier for a cone - either by name or UUID */
export type ConeIdentifier = ConeIdentifierByName | ConeIdentifierById;

export function isConeIdentifierByName(e: ConeIdentifier): e is ConeIdentifierByName { return e.type === 'by_name'; }
export function isConeIdentifierById(e: ConeIdentifier): e is ConeIdentifierById { return e.type === 'by_id'; }

/** Lightweight cone info (for listing) */
export interface ConeInfo {
  createdAt: number;
  head: Position;
  id: string;
  modelId: string;
  name: string;
}

export interface Constraints {
  maxFunctionCallsPerMessage?: number | null;
  maxImageSizeMb?: number | null;
  maxImagesPerMessage?: number | null;
  supportedImageFormats?: string[];
}

export interface CreateResultConeCreated {
  type: 'cone_created';
  coneId: string;
  /** Initial position (tree + root node) */
  head: Position;
}

export interface CreateResultError {
  type: 'error';
  message: string;
}

/** Result of cone.create */
export type CreateResult = CreateResultConeCreated | CreateResultError;

export function isCreateResultConeCreated(e: CreateResult): e is CreateResultConeCreated { return e.type === 'cone_created'; }
export function isCreateResultError(e: CreateResult): e is CreateResultError { return e.type === 'error'; }

/** Currency for pricing */
export type Currency = "USD" | "EUR" | "GBP";

export interface DeleteResultConeDeleted {
  type: 'cone_deleted';
  coneId: string;
}

export interface DeleteResultError {
  type: 'error';
  message: string;
}

/** Result of cone.delete */
export type DeleteResult = DeleteResultConeDeleted | DeleteResultError;

export function isDeleteResultConeDeleted(e: DeleteResult): e is DeleteResultConeDeleted { return e.type === 'cone_deleted'; }
export function isDeleteResultError(e: DeleteResult): e is DeleteResultError { return e.type === 'error'; }

export interface GetResultConeData {
  type: 'cone_data';
  cone: ConeConfig;
}

export interface GetResultError {
  type: 'error';
  message: string;
}

/** Result of cone.get */
export type GetResult = GetResultConeData | GetResultError;

export function isGetResultConeData(e: GetResult): e is GetResultConeData { return e.type === 'cone_data'; }
export function isGetResultError(e: GetResult): e is GetResultError { return e.type === 'error'; }

export interface ListResultConeList {
  type: 'cone_list';
  cones: ConeInfo[];
}

export interface ListResultError {
  type: 'error';
  message: string;
}

/** Result of cone.list */
export type ListResult = ListResultConeList | ListResultError;

export function isListResultConeList(e: ListResult): e is ListResultConeList { return e.type === 'cone_list'; }
export function isListResultError(e: ListResult): e is ListResultError { return e.type === 'error'; }

/** Message builder format - determines how messages are structured for the API */
export type MessageFormat = never;

/** Serializable model information */
export interface ModelExport {
  /** Model capabilities */
  capabilities: Capabilities;
  /** Model constraints */
  constraints: Constraints;
  /** Model family (e.g., "claude", "gpt") */
  family: string;
  /** Model identifier */
  id: string;
  /** Lab/organization that created the model */
  lab?: string | null;
  /** Human-readable name */
  name: string;
  /** Pricing information */
  pricing: Pricing;
  /** Service this model uses */
  service: string;
  /** Verification status */
  status: VerificationStatus;
  /** Use cases this model is suited for */
  useCases: string[];
  /** Variant (e.g., "haiku", "sonnet", "opus") */
  variant?: string | null;
  /** Version string if available */
  version?: string | null;
}

/** A position in the context tree - couples tree_id and node_id together.
This ensures we always have a valid reference into a specific tree. */
export interface Position {
  /** The specific node within the tree */
  nodeId: UUID;
  /** The tree containing this position */
  treeId: UUID;
}

export interface Pricing {
  cachedInputPer1kTokens?: number | null;
  currency?: Currency;
  inputPer1kTokens: number;
  outputPer1kTokens: number;
}

/** Serializable rate limits */
export interface RateLimitsExport {
  concurrentRequests?: number | null;
  requestsPerMinute?: number | null;
  tokensPerMinute?: number | null;
}

/** Complete registry export - all services, families, and models in one structure */
export interface RegistryExport {
  /** All model families (e.g., "claude", "gpt", "deepseek") */
  families: string[];
  /** All available models */
  models: ModelExport[];
  /** All available services */
  services: ServiceExport[];
  /** Summary statistics */
  stats: RegistryStats;
}

export interface RegistryResultRegistry {
  type: 'registry';
}

/** Result of cone.registry */
export type RegistryResult = RegistryResultRegistry;

export function isRegistryResultRegistry(e: RegistryResult): e is RegistryResultRegistry { return e.type === 'registry'; }

/** Summary statistics about the registry */
export interface RegistryStats {
  /** Total number of model families */
  familyCount: number;
  /** Total number of models */
  modelCount: number;
  /** Total number of services */
  serviceCount: number;
  /** Number of unverified models */
  unverifiedCount: number;
  /** Number of verified models */
  verifiedCount: number;
}

/** Serializable service information */
export interface ServiceExport {
  /** Base URL for the API */
  baseUrl: string;
  /** Message format type */
  messageFormat: MessageFormat;
  /** Number of models using this service */
  modelCount: number;
  /** Service identifier (e.g., "openai", "anthropic") */
  name: string;
  /** Rate limits if configured */
  rateLimits?: RateLimitsExport | null;
}

export interface SetHeadResultHeadUpdated {
  type: 'head_updated';
  coneId: string;
  newHead: Position;
  oldHead: Position;
}

export interface SetHeadResultError {
  type: 'error';
  message: string;
}

/** Result of cone.set_head */
export type SetHeadResult = SetHeadResultHeadUpdated | SetHeadResultError;

export function isSetHeadResultHeadUpdated(e: SetHeadResult): e is SetHeadResultHeadUpdated { return e.type === 'head_updated'; }
export function isSetHeadResultError(e: SetHeadResult): e is SetHeadResultError { return e.type === 'error'; }

export type UUID = string;

/** Verification status for a model configuration */
export type VerificationStatus = "verified" | "unverified" | "broken" | "deprecated" | "error" | "not_found";
